# Generated by Django 4.1.5 on 2023-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('received_quantity', models.IntegerField(blank=True, default='0')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0')),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
